### PR TITLE
#1 changes to support logging in via SSH

### PR DESCRIPTION
**Pull request by partouf**
Any ideas on how to make this code better?
* Currently .ssh/id_rsa and id_rsa.pub is hardcoded
* It's always used

Would like to make it optional, and the ability to setup the paths where your priv/pub key files are...

### CODE REVIEW

**Review by martinvd — APPROVED** [review]
Cool 👍

**Comment by martinvd** [comment]
I will try to test it

**Comment by partouf** [comment]
merging so I can whip up some interfaces and configuration things

**Comment by martinvd** [comment]
:+1:

**Pull request merged**
